#!/bin/bash
# UNCOMMENT EVERYTHING. This is just a workaround around https://github.com/nodesource/distributions/issues/1266
# set -e
# 
# # fixing certificate error from around 01.10.2021 https://github.com/nodesource/distributions/issues/1266
# apt update
# apt install ca-certificates
# apt install libgnutls30
# 
# # enabling WebIO
# conda install nodejs
# julia -e '
#     using WebIO, IJulia
#     # WebIO.install_jupyter_labextension()  # does rais errors currently
#     WebIO.install_jupyter_nbextension()
#     println("Installed WebIO jupyter extensions.")
# '