#!/bin/bash
set -e

# enabling WebIO
conda install nodejs
julia -e '
    using WebIO, IJulia
    # WebIO.install_jupyter_labextension()  # does rais errors currently
    WebIO.install_jupyter_nbextension()
    println("Installed WebIO jupyter extensions.")
'